version: '3'

services:
  # Nifi cluster
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181
    networks:
      game_data_net:
    volumes:
      - ./zookeeper/secrets:/etc/zookeeper/secrets
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/log:/var/lib/zookeeper/log

  nifi01:
    image: apache/nifi
    container_name: nifi01
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
    ports:
      - 6980:8080
    networks:
      game_data_net:
    volumes:
      - nifi01_conf:/opt/nifi/nifi-current/conf
      - nifi01_logs:/opt/nifi/nifi-current/logs
      - nifi01_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi01_state:/opt/nifi/nifi-current/state
      - nifi01_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi01_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi01_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository

  nifi02:
    image: apache/nifi
    container_name: nifi02
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
    ports:
      - 6979:8080
    networks:
      game_data_net:
    volumes:
      - nifi02_conf:/opt/nifi/nifi-current/conf
      - nifi02_logs:/opt/nifi/nifi-current/logs
      - nifi02_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi02_state:/opt/nifi/nifi-current/state
      - nifi02_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi02_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi02_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository

  # HDFS cluster
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env
    restart: always
    networks:
      game_data_net:
    volumes:
      - hadoop_home:/home
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop/hadoop.env
    restart: always
    networks:
      game_data_net:
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  # Spark cluster
  spark-master:
    image: bitnami/spark
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8888:8080
    networks:
      game_data_net:
    volumes:
      - ./spark:/opt/code
      
  spark-worker:
    image: bitnami/spark
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      game_data_net:
    volumes:
      - ./spark:/opt/code

  # Other
  data-warehouse:
    image: postgres
    container_name: data-warehouse
    environment:
      - POSTGRES_USER=datawarehouse
      - POSTGRES_PASSWORD=datawarehouse
      - POSTGRES_DB=datawarehouse
    ports:
      - 15432:5432
    networks:
      game_data_net:
    volumes:
      - data-warehouse:/var/lib/postgresql/data

  superset:
    build: ./superset
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=secret
    ports:
      - 8088:8088
    networks:
      game_data_net:
    volumes:
      - superset_data:/app/superset_home

networks:
  game_data_net:

volumes:
  nifi01_conf:
  nifi01_logs:
  nifi01_provenance_repository:
  nifi01_state:
  nifi01_content_repository:
  nifi01_database_repository:
  nifi01_flowfile_repository:

  nifi02_conf:
  nifi02_logs:
  nifi02_provenance_repository:
  nifi02_state:
  nifi02_content_repository:
  nifi02_database_repository:
  nifi02_flowfile_repository:
  
  hadoop_home:
  hadoop_namenode:
  hadoop_datanode:
  data-warehouse:
  superset_data: